package die

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math/rand"
	"os"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"
)

func analysisFixture(t testing.TB, n int, pairs [][2]int) (DependencyInventory, []string) {
	t.Helper()
	input := GraphInput{}
	ids := make([]string, n)
	for j := 0; j < n; j++ {
		v := testNode(fmt.Sprintf("p%d", j), fmt.Sprintf("p%d", j))
		v.Evidence = nil
		input.Nodes = append(input.Nodes, v)
		ids[j] = nodeID(v.Identity)
	}
	for _, p := range pairs {
		input.Dependencies = append(input.Dependencies, DependencyCandidate{Graph: GraphPackage, Kind: DependencyImports, From: input.Nodes[p[0]].Identity, To: input.Nodes[p[1]].Identity, Resolution: ResolvedLocal})
	}
	inv, e := newTestCore(t, ConfigParams{}).Normalize(context.Background(), input)
	if e != nil {
		t.Fatal(e)
	}
	return inv, ids
}
func analysisDefault(t testing.TB) *graphAnalyzer {
	t.Helper()
	c, e := NewAnalysisConfig(AnalysisConfigParams{})
	if e != nil {
		t.Fatal(e)
	}
	return &graphAnalyzer{c}
}
func impactQ(t testing.TB, ids []string, dir TraversalDirection, depth uint32, n, e uint64) ImpactQuery {
	t.Helper()
	q, err := NewImpactQuery(ImpactQueryParams{NodeIDs: ids, Graph: GraphPackage, Direction: dir, MaxDepth: depth, MaxNodes: n, MaxEdges: e})
	if err != nil {
		t.Fatal(err)
	}
	return q
}
func nodeQ(t testing.TB, id string, size uint32, cursor string) NodeQuery {
	t.Helper()
	q, e := NewNodeQuery(NodeQueryParams{id, GraphPackage, size, cursor})
	if e != nil {
		t.Fatal(e)
	}
	return q
}

func TestAnalysisIndependentVectors(t *testing.T) {
	// Expected values are read verbatim from the independently committed document,
	// not generated by production encoding or by a second use of this encoder.
	doc, e := os.ReadFile("../../docs/API/DEPENDENCY_ANALYSIS_GOLDEN_VECTORS.md")
	if e != nil {
		t.Fatal(e)
	}
	blocks := regexp.MustCompile("(?s)```text\\r?\\n(.*?)\\r?\\n```").FindAllStringSubmatch(string(doc), -1)
	if len(blocks) != 5 {
		t.Fatal("frozen vectors missing")
	}
	inv, _ := analysisFixture(t, 0, nil)
	d, e := analysisFingerprint(context.Background(), inv.view)
	if e != nil || d != blocks[0][1] {
		t.Fatalf("empty digest %s %v", d, e)
	}
	inv.view.SourceArtifacts = []ArtifactReference{{Name: "fixture/π<&", Version: "1.0.0"}}
	inv.view.Statistics.OmittedEdges = 1
	d2, e := analysisFingerprint(context.Background(), inv.view)
	if e != nil || d2 != blocks[1][1] {
		t.Fatalf("unicode digest %s %v", d2, e)
	}
	a, b := "dependency-node-id/v1:sha256:"+strings.Repeat("a", 64), "dependency-node-id/v1:sha256:"+strings.Repeat("b", 64)
	for i, c := range []struct {
		d    string
		g    GraphKind
		dir  TraversalDirection
		root string
		size uint32
		last string
	}{{d, GraphPackage, Dependencies, a, 100, b}, {d2, GraphPackage, Dependencies, a, 100, b}, {d, GraphFile, Dependents, b, 1, a}} {
		got := pageCursor(c.d, c.g, c.dir, c.root, c.size, c.last)
		if got != blocks[i+2][1] {
			t.Fatalf("cursor vector %d", i)
		}
		last, e := cursorLast(got, c.d, c.g, c.dir, c.root, c.size)
		if e != nil || last != c.last {
			t.Fatal(last, e)
		}
	}
	s := stableID("dependency-scc-id/v1", "package", "a", "β")
	if s != "dependency-scc-id/v1:sha256:360e477842ffa8936cb211fa0ef8e621043e3f06105f680537a5d478d7f0a2f8" {
		t.Fatal(s)
	}
	if c := stableID("dependency-cycle-id/v1", "package", s); c != "dependency-cycle-id/v1:sha256:455fdfe1396a0c675860713ff4be826465b6eb83982e3bd7ecce66734c42eb8c" {
		t.Fatal(c)
	}
}

func TestAnalysisOracle(t *testing.T) {
	for seed := int64(0); seed < 100; seed++ {
		r := rand.New(rand.NewSource(seed))
		n := 1 + r.Intn(12)
		pairs := [][2]int{}
		reach := make([][]bool, n)
		for i := range reach {
			reach[i] = make([]bool, n)
			reach[i][i] = true
			for j := 0; j < n; j++ {
				if r.Intn(5) == 0 {
					pairs = append(pairs, [2]int{i, j})
					reach[i][j] = true
				}
			}
		}
		// Floyd-Warshall equivalence is independent of iterative Tarjan.
		for k := 0; k < n; k++ {
			for i := 0; i < n; i++ {
				for j := 0; j < n; j++ {
					reach[i][j] = reach[i][j] || (reach[i][k] && reach[k][j])
				}
			}
		}
		inv, ids := analysisFixture(t, n, pairs)
		out, e := analysisDefault(t).Analyze(context.Background(), inv)
		if e != nil {
			t.Fatal(e)
		}
		component := map[string]string{}
		cyclic := 0
		for _, c := range out.StrongComponents() {
			if c.Cyclic {
				cyclic++
			}
			for _, id := range c.NodeIDs {
				if component[id] != "" {
					t.Fatal("duplicate membership")
				}
				component[id] = c.ID
			}
		}
		if len(component) != n || cyclic != len(out.Cycles()) {
			t.Fatal("partition/cycles")
		}
		for i := 0; i < n; i++ {
			for j := 0; j < n; j++ {
				if (component[ids[i]] == component[ids[j]]) != (reach[i][j] && reach[j][i]) {
					t.Fatalf("oracle seed=%d i=%d j=%d", seed, i, j)
				}
			}
		}
		for _, dir := range []TraversalDirection{Dependencies, Dependents} {
			// Repeated edge relaxation supplies an independent shortest-depth
			// oracle, rather than another breadth-first implementation.
			distance := make([]int, n)
			for j := 1; j < n; j++ {
				distance[j] = n + 1
			}
			for pass := 0; pass < n; pass++ {
				for _, p := range pairs {
					from, to := p[0], p[1]
					if dir == Dependents {
						from, to = to, from
					}
					if distance[from]+1 < distance[to] {
						distance[to] = distance[from] + 1
					}
				}
			}
			got, e := analysisDefault(t).Impact(context.Background(), inv, impactQ(t, ids[:1], dir, 64, 0, 0))
			if e != nil {
				t.Fatal(e)
			}
			set := map[string]bool{}
			for _, v := range got.View().Reached {
				set[v.NodeID] = true
				for j, id := range ids {
					if id == v.NodeID && int(v.Depth) != distance[j] {
						t.Fatalf("shortest depth seed=%d node=%d", seed, j)
					}
				}
			}
			for j := 1; j < n; j++ {
				want := reach[0][j]
				if dir == Dependents {
					want = reach[j][0]
				}
				if set[ids[j]] != want {
					t.Fatalf("BFS oracle %d", seed)
				}
			}
		}
	}
}

func TestAnalysisQueriesLimitsAndCopies(t *testing.T) {
	inv, ids := analysisFixture(t, 5, [][2]int{{0, 1}, {0, 2}, {1, 3}, {2, 3}, {3, 4}, {4, 0}})
	a := analysisDefault(t)
	ctx := context.Background()
	first, e := a.DirectDependencies(ctx, inv, nodeQ(t, ids[0], 1, ""))
	if e != nil {
		t.Fatal(e)
	}
	v := first.View()
	if len(v.Neighbors) != 1 || !v.HasMore || v.NextCursor == "" {
		t.Fatal(v)
	}
	second, e := a.DirectDependencies(ctx, inv, nodeQ(t, ids[0], 1, v.NextCursor))
	if e != nil || second.View().HasMore || len(second.View().Neighbors) != 1 {
		t.Fatal(second, e)
	}
	v.Neighbors[0].EdgeIDs[0] = "bad"
	v.ReasonCodes = append(v.ReasonCodes, "bad")
	if first.View().Neighbors[0].EdgeIDs[0] == "bad" {
		t.Fatal("page alias")
	}
	if _, e = json.Marshal(first); e != nil {
		t.Fatal(e)
	}
	incoming, e := a.DirectDependents(ctx, inv, nodeQ(t, ids[3], 100, ""))
	if e != nil || len(incoming.View().Neighbors) != 2 {
		t.Fatal(incoming, e)
	}
	for _, q := range []NodeQuery{nodeQ(t, ids[0], 2, first.View().NextCursor), nodeQ(t, ids[1], 1, first.View().NextCursor), nodeQ(t, ids[0], 1, "bad"), nodeQ(t, ids[0], 1, first.View().NextCursor+"=")} {
		if _, e = a.DirectDependencies(ctx, inv, q); e == nil {
			t.Fatal("cursor accepted")
		}
	}
	changed := DependencyInventory{cloneView(inv.view)}
	changed.view.Statistics.OmittedEvidence++
	if _, e = a.DirectDependencies(ctx, changed, nodeQ(t, ids[0], 1, first.View().NextCursor)); e == nil {
		t.Fatal("changed digest accepted")
	}
	for _, tc := range []struct {
		d      uint32
		n, e   uint64
		reason string
	}{{1, 0, 0, "depth_limit"}, {64, 1, 0, "node_limit"}, {64, 0, 1, "edge_limit"}} {
		r, e := a.Impact(ctx, inv, impactQ(t, ids[:1], Dependencies, tc.d, tc.n, tc.e))
		if e != nil {
			t.Fatal(e)
		}
		w := r.View()
		if !w.Truncated || !strings.Contains(strings.Join(w.ReasonCodes, ","), tc.reason) {
			t.Fatal(w)
		}
		if tc.n > 0 && w.VisitedNodes > tc.n || tc.e > 0 && w.ScannedEdges > tc.e {
			t.Fatal("exceeded")
		}
	}
	seeds := []string{ids[0], ids[0], ids[2]}
	q := impactQ(t, seeds, Dependencies, 64, 0, 0)
	seeds[0] = "bad"
	r, e := a.Impact(ctx, inv, q)
	if e != nil {
		t.Fatal(e)
	}
	rv := r.View()
	if len(rv.Seeds) != 2 || len(rv.Reached) != 3 || rv.Truncated {
		t.Fatal(rv)
	}
	rv.Seeds[0] = "bad"
	rv.Reached[0].NodeID = "bad"
	rv.EdgeIDs[0] = "bad"
	if r.View().Seeds[0] == "bad" || r.View().Reached[0].NodeID == "bad" {
		t.Fatal("impact alias")
	}
	json.Marshal(r)
	before, _ := json.Marshal(inv)
	out, e := a.Analyze(ctx, inv)
	if e != nil {
		t.Fatal(e)
	}
	again, e := a.Analyze(ctx, out)
	if e != nil || !reflect.DeepEqual(out.View(), again.View()) {
		t.Fatal("reanalysis differs", e)
	}
	after, _ := json.Marshal(inv)
	if string(before) != string(after) || strings.Contains(string(before), "\"analysis\"") {
		t.Fatal("core mutated")
	}
	meta := out.Analysis()
	meta.Graphs[0].ReasonCodes = append(meta.Graphs[0].ReasonCodes, "bad")
	meta.EngineName = "bad"
	view := out.View()
	view.Analysis.Graphs[0].Graph = "bad"
	if out.Analysis().EngineName == "bad" || out.Analysis().Graphs[0].Graph == "bad" {
		t.Fatal("analysis alias")
	}
	var wg sync.WaitGroup
	for j := 0; j < 16; j++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			if _, e := a.Analyze(ctx, inv); e != nil {
				t.Error(e)
			}
			if _, e := a.Impact(ctx, inv, q); e != nil {
				t.Error(e)
			}
		}()
	}
	wg.Wait()
}

func TestAnalysisBoundaryPromotion(t *testing.T) {
	inv, ids := analysisFixture(t, 3, [][2]int{{0, 1}, {1, 2}})
	edge := inv.view.Dependencies[0]
	for _, e := range inv.view.Dependencies {
		if e.FromNodeID == ids[0] {
			edge = e
		}
	}
	edge.Resolution = Ambiguous
	edge.ID = edgeID(edge.Graph, edge.Kind, edge.FromNodeID, edge.ToNodeID, edge.Resolution)
	inv.view.Dependencies = append(inv.view.Dependencies, edge)
	a := analysisDefault(t)
	r, e := a.Impact(context.Background(), inv, impactQ(t, ids[:1], Dependencies, 64, 0, 0))
	if e != nil || len(r.View().Reached) != 2 || len(r.View().BoundaryNodeIDs) != 0 || !r.View().TopologyLimited {
		t.Fatal(r, e)
	}
	// With only the uncertain first hop, no later local vertex may be reached.
	for j, e := range inv.view.Dependencies {
		if e.FromNodeID == ids[0] && e.Resolution == ResolvedLocal {
			inv.view.Dependencies = append(inv.view.Dependencies[:j], inv.view.Dependencies[j+1:]...)
			break
		}
	}
	r, e = a.Impact(context.Background(), inv, impactQ(t, ids[:1], Dependencies, 64, 0, 0))
	if e != nil || len(r.View().Reached) != 0 || !reflect.DeepEqual(r.View().BoundaryNodeIDs, []string{ids[1]}) {
		t.Fatal(r, e)
	}
}

func TestAnalysisValidationAndCancellation(t *testing.T) {
	a := analysisDefault(t)
	inv, ids := analysisFixture(t, 3, [][2]int{{0, 1}, {1, 0}, {2, 2}})
	for _, mutate := range []func(*DependencyInventoryView){func(v *DependencyInventoryView) { v.Artifact.Version = "bad" }, func(v *DependencyInventoryView) { v.Nodes = append(v.Nodes, v.Nodes[0]) }, func(v *DependencyInventoryView) { v.Nodes[0].ID = "bad" }, func(v *DependencyInventoryView) { v.Dependencies[0].ToNodeID = "bad" }, func(v *DependencyInventoryView) { v.Dependencies[0].Graph = "bad" }, func(v *DependencyInventoryView) { v.Dependencies = append(v.Dependencies, v.Dependencies[0]) }} {
		v := cloneView(inv.view)
		mutate(&v)
		out, e := a.Analyze(context.Background(), DependencyInventory{v})
		if e == nil || out.view.Artifact.Name != "" {
			t.Fatal("bad input accepted")
		}
	}
	for _, p := range []AnalysisConfigParams{{MaxInputNodes: 1, MaxComponents: 1, MaxCycles: 1, MaxTraversalNodes: 1}, {MaxInputEdges: 1, MaxTraversalEdges: 1}, {MaxComponents: 1, MaxCycles: 1}, {MaxCycles: 1}} {
		c, e := NewAnalysisConfig(p)
		if e != nil {
			t.Fatal(e)
		}
		out, e := (&graphAnalyzer{c}).Analyze(context.Background(), inv)
		if e == nil || out.view.Artifact.Name != "" {
			t.Fatal("hard limit")
		}
	}
	canceled, cancel := context.WithCancel(context.Background())
	cancel()
	expired, cancel2 := context.WithDeadline(context.Background(), time.Time{})
	defer cancel2()
	for _, ctx := range []context.Context{nil, canceled, expired} {
		if _, e := a.Analyze(ctx, inv); e == nil {
			t.Fatal("context")
		}
		if _, e := a.DirectDependencies(ctx, inv, nodeQ(t, ids[0], 0, "")); e == nil {
			t.Fatal("context")
		}
		if _, e := a.Impact(ctx, inv, impactQ(t, ids[:1], Dependencies, 0, 0, 0)); e == nil {
			t.Fatal("context")
		}
	}
	if _, e := a.Analyze(canceled, inv); !errors.Is(e, context.Canceled) {
		t.Fatal(e)
	}
	if _, e := a.Analyze(expired, inv); !errors.Is(e, context.DeadlineExceeded) {
		t.Fatal(e)
	}
	if _, e := NewAnalyzer(AnalysisConfig{}); e == nil {
		t.Fatal("zero config")
	}
	if _, e := NewQueryEngine(AnalysisConfig{}); e == nil {
		t.Fatal("zero config")
	}
	NewAnalyzer(a.config)
	NewQueryEngine(a.config)
	for _, p := range []AnalysisConfigParams{{MaxInputNodes: ^uint64(0)}, {MaxTraversalDepth: 4097}, {MaxPageSize: 1001}, {MaxInputNodes: 1}, {MaxInputEdges: 1}} {
		if _, e := NewAnalysisConfig(p); e == nil {
			t.Fatal("invalid config")
		}
	}
	for _, p := range []NodeQueryParams{{}, {NodeID: ids[0], Graph: GraphPackage, PageSize: 1001}, {NodeID: ids[0], Graph: GraphPackage, Cursor: strings.Repeat("x", 2049)}} {
		if _, e := NewNodeQuery(p); e == nil {
			t.Fatal("invalid node query")
		}
	}
	for _, p := range []ImpactQueryParams{{}, {NodeIDs: []string{"bad"}, Graph: GraphPackage, Direction: Dependencies}, {NodeIDs: ids, Graph: GraphPackage, Direction: "bad"}} {
		if _, e := NewImpactQuery(p); e == nil {
			t.Fatal("invalid impact")
		}
	}
	if _, e := a.DirectDependencies(context.Background(), inv, NodeQuery{}); e == nil {
		t.Fatal("zero query")
	}
	if _, e := a.Impact(context.Background(), inv, ImpactQuery{}); e == nil {
		t.Fatal("zero impact")
	}
	c := a.config
	if c.MaxInputNodes() == 0 || c.MaxInputEdges() == 0 || c.MaxInputEvidence() == 0 || c.MaxInputAuxRecords() == 0 || c.MaxComponents() == 0 || c.MaxCycles() == 0 || c.MaxTraversalNodes() == 0 || c.MaxTraversalEdges() == 0 || c.MaxTraversalDepth() == 0 || c.MaxPageSize() == 0 {
		t.Fatal("getters")
	}
}

func TestAnalysisPartialAndDeep(t *testing.T) {
	inv, _ := analysisFixture(t, 0, nil)
	inv.view.Statistics.OmittedNodes = 1
	inv.view.Statistics.OmittedEdges = 1
	inv.view.Statistics.OmittedDiagnostics = 1
	inv.view.Statistics.OmittedEvidence = 1
	inv.view.Statistics.OmittedContainment = 1
	inv.view.Diagnostics = []Diagnostic{{Code: "future-code"}}
	out, e := analysisDefault(t).Analyze(context.Background(), inv)
	if e != nil {
		t.Fatal(e)
	}
	for _, g := range out.Analysis().Graphs {
		if !g.TopologyLimited || !g.ExplanationLimited || len(g.ReasonCodes) != 6 {
			t.Fatal(g)
		}
	}
	pairs := make([][2]int, 9999)
	for j := range pairs {
		pairs[j] = [2]int{j, j + 1}
	}
	deep, _ := analysisFixture(t, 10000, pairs)
	out, e = analysisDefault(t).Analyze(context.Background(), deep)
	if e != nil || len(out.StrongComponents()) != 10000 || len(out.Cycles()) != 0 {
		t.Fatal("deep chain", e)
	}
}

func FuzzAnalysisGraph(f *testing.F) {
	f.Add([]byte{1, 2, 3, 4})
	f.Fuzz(func(t *testing.T, b []byte) {
		if len(b) > 64 {
			b = b[:64]
		}
		pairs := [][2]int{}
		for j := 1; j < len(b); j += 2 {
			pairs = append(pairs, [2]int{int(b[j-1] % 8), int(b[j] % 8)})
		}
		inv, ids := analysisFixture(t, 8, pairs)
		a := analysisDefault(t)
		out, e := a.Analyze(context.Background(), inv)
		if e != nil {
			t.Fatal(e)
		}
		members := []string{}
		for _, s := range out.StrongComponents() {
			members = append(members, s.NodeIDs...)
		}
		sort.Strings(members)
		sort.Strings(ids)
		if !reflect.DeepEqual(ids, members) {
			t.Fatal("partition")
		}
		depth, nodes, edges, dir := uint32(2), uint64(3), uint64(5), Dependencies
		if len(b) > 3 {
			depth = 1 + uint32(b[0]%8)
			nodes = 1 + uint64(b[1]%8)
			edges = 1 + uint64(b[2]%64)
			if b[3]%2 == 1 {
				dir = Dependents
			}
		}
		result, e := a.Impact(context.Background(), inv, impactQ(t, ids[:1], dir, depth, nodes, edges))
		if e != nil {
			t.Fatal(e)
		}
		v := result.View()
		if v.VisitedNodes > nodes || v.ScannedEdges > edges || v.MaxDepthReached > depth {
			t.Fatal("fuzz budget exceeded")
		}
	})
}
func FuzzAnalysisCursor(f *testing.F) {
	f.Add("bad")
	f.Add("")
	f.Fuzz(func(t *testing.T, s string) {
		if len(s) > 2050 {
			return
		}
		id := "dependency-node-id/v1:sha256:" + strings.Repeat("a", 64)
		last, e := cursorLast(s, "digest", GraphPackage, Dependencies, id, 1)
		if e == nil && pageCursor("digest", GraphPackage, Dependencies, id, 1, last) != s {
			t.Fatal("noncanonical")
		}
	})
}
